### ISSUE TITLE
Select API endpoints (setup) -- Eileen, TJ, Joseph

### ISSUE THREAD

**Issue by Namewastook** [goldblade23/Kwitter#5]
Decide as a group what API endpoints to hit.
Minimum of 10 needed.

**Comment by etallman** [comment]
SELECTED:
REGISTER NEW USER
LOGIN
LOGOUT
CREATE MESSAGE
GET MESSAGES
GET MESSAGE BY ID
DELETE MESSAGE BY ID
GET USER BY ID
UPDATE USER
DELETE CURRENTLY AUTHENTICATED...
SET USER PROFILE PICTURE

**Any additional endpoints will be added with features**
