### ISSUE TITLE
FEED MESSAGES () --

### ISSUE THREAD

**Issue by etallman** [goldblade23/Kwitter#56]
TJ, Joseph worked on, resolved with Taylor
USER STORY:
User should be able to add a message to their feed by adding text to an input box and pushing a submit button. The user should be able to see their latest message on their feed page.

ACCEPTANCE CRITERIA:
New messages should be displayed on the feed and should not disappear when refreshed.

TECHNICAL NOTES:
Need text area, click handler for submit button, and feed components.
API endpoint -- GET MESSAGES (GET MESSAGE BY ID AND DELETE MESSAGE BY ID?)

**Comment by Namewastook** [comment]
Updated the card to include those who worked on finishing the component(s)
